CC = mingw32-gcc.exe
FLEX = win_flex_bison\win_flex.exe
BISON = win_flex_bison\win_bison.exe
RM = del /f /q
TARGETS := spli

all: $(TARGETS)

$(TARGETS):
	$(BISON) -d spli.y
	$(FLEX) spli.l
	$(CC) -o bin\spli.exe lex.yy.c spli.tab.c spli.c prop.c

debug:
	$(BISON) -d spli.y
	$(FLEX) -d spli.l
	$(CC) -o bin\spli.exe lex.yy.c spli.tab.c spli.c prop.c
	
clean:
	$(RM) lex.yy.c spli.tab.c spli.tab.h bin\spli.exe
